[package]
name = "lights"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = "*"
serde = { version = "1.0.194", features = ["serde_derive"] }
serde_json = "1.0.68"
rand = "0.8.5"
