(define-module (home lights)
  #:use-module (vup rust-import-lock)
  #:use-module (gnu packages crates-io)
  #:use-module (gnu packages crates-web)
  #:use-module (gnu packages crates-tls)
  #:use-module (gnu packages crates-windows)
  #:use-module (gnu packages crates-crypto)
  #:use-module (guix gexp)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix build-system cargo)
  #:use-module ((guix licenses) #:prefix license:)
  #:export (lights))

(define-public lights
  (package
    (name "lights")
    (version "0.1.0")
    (source
      (local-file "./lights" #:recursive? #t))
    (build-system cargo-build-system)
    (inputs (import-rust-lock source))
    (home-page "--")
    (synopsis "lights control daemon")
    (description "lights control daemon")
    (license (list license:gpl2))))
